### BONJOUR FÉLIX, ICI JEAN-HUGUES ROY
### TOUS MES COMMENTAIRES SERONT EN MAJUSCULES ET PRÉCÉDÉS DE 3 # (HASHTAGS)

url = "https://montrealcampus.ca?p=30145"
# BASE = (url[:28]) ### ATTENTION: IL EST PRÉFÉRABLE D'UTILISER DES NOMS DE VARIABLES EN MINUSCULES
base = (url[:28])
# print (BASE + ID)
# ID = [] ### ICI AUSSI
id = [] 
for x in range(20000,30151):
    # ID.append(BASE + str(x)) ### IDEM
    id.append(base + str(x))
# print (ID) ### ÇA FONCTIONNE QUAND MÊME, MAIS ÉVITE DE METTRE UN ESPACE ENTRE LE NOM DE LA FONCTION ET LES PARENTHÈSES QUI CONTIENNENT SES PARAMÈTRES
print(id)
# print (len(ID))
print(len(id))

### BRAVO! HORMIS QUELQUES DÉTAILS SOULIGNÉS CI-DESSUS, C'EST EXACTEMENT CE QU'IL FALLAIT FAIRE!
### EN OUTRE, PRENDS L'HABITUDE D'ÉCRIRE DES COMMENTAIRES POUR PERMETTRE À QUELQU'UN D'AUTRE DE COMPRENDRE CE QUE TU FAIS DANS TON CODE. 